namespace :data_updates do
    task add_defaults: :environment do
      AbilityScore.all.each do |x|
        x.ability = ""
        x.value_range = ""
        x.feat_of_strength = 0
        x.lift = 0
        x.carry = 0
        x.drag = 0
        x.damage_mod = 0
        x.init_mod = 0
        x.speed_mod = 0
        x.attack_mod = 0
        x.defense_mod = 0
        x.turning_mod = 0
        x.feat_of_agility = 0
        x.mental_saving_throw_bonus = 0
        x.dodge_saving_throw_bonus = 0
        x.physical_saving_throw_bonus = 0
        x.morale_mod = 0
        x.min = 0
        x.max = 0
        x.max_spells_per_level = 0
        x.chance_to_learn_spell = 0
      end

      Character.all.each do |x|
        x.strength = 0
        x.intelligence = 0
        x.wisdom = 0
        x.dexterity = 0
        x.constitution = 0
        x.looks = 0
        x.charisma = 0
        x.honor = 0
        x.fame = 0
        x.health = 0
        x.name = ""
        x.alignment = "LG"
        x.sex = "M"
        x.age = 0
        x.height = 0
        x.weight = 0
        x.hair = "black"
        x.eyes = "brown"
        x.handedness = "L"
        x.trade_coins = ""
        x.copper = 0
        x.silver = 0
        x.gold = 0
        x.user_id = 0
        x.mentor_id = 0
        x.left_hand_item_id = 0
        x.right_hand_item_id = 0
        x.body_item_id = 0
        x.character_class_id = 0
        x.race_id = 0
        x.finished = false
      end

      ItemInstance.all.each do |x|
        x.durability = 0
        x.attack_mod = 0
        x.speed_mod = 0
        x.init_mod = 0
        x.defense_mod = 0
        x.damage_mod = 0
        x.damage_reduction = 0
        x.magic_level = 0
        x.init_die_mod = 0
        x.display = false
        x.name = ""
      end

      Item.all.each do |x|
        x.attack_mod = 0
        x.speed_mod = 0
        x.init_mod = 0
        x.defense_mod = 0
        x.damage_mod = 0
        x.damage_reduction = 0
        x.magic_level = 0
        x.weight = 0
        x.cover_value = 0
        x.location = "arm"
        x.damage = ""
        x.shield_size = ""
        x.armor_type = ""
        x.name = ""
        x.description = ""
        x.attack_speed = 0
        x.jab_speed = 0
        x.reach = 0
        x.buy_cost = 0
        x.sell_value = 0
        x.damage_type = ""
        x.heal_value = 0
        x.item_type = ""
        x.high_avail = 0
        x.med_avail = 0
        x.low_avail = 0
        x.init_die_mod = 0
        x.movement_rate_reduction = 0
        x.crouching_cover_value = 0
        x.shield_damage = ""
        x.str_required = 0
        x.skill_level = ""
        x.dismount = false
        x.heavy_armor = 0
        x.set_for_charge = false
        x.pole_arm_defense = ""
        x.phalanx = 0
        x.size = ""
        x.max_range = 0
        x.range_short = 0
        x.range_medium = 0
        x.range_long = 0
        x.range_maximum = 0
        x.proficiency_id = 0
        x.two_handed = false
        x.mounted = false
        x.sword = false
        x.capacity_pounds = 0
        x.capacity_gallons = 0
        x.number_of_days = 0
        x.requires_preparation = false
        x.distance = 0
      end

      Level.all.each do |x|
        x.level_value = 0
        x.init_mod = 0
        x.attack_mod = 0
        x.speed_mod = 0
        x.spell_points = 0
        x.stvsspells = 0
        x.added_spells = ""
        x.ranged_speed_mod = 0
        x.init_die_mod = 0
        x.hit_dice = ""
      end

      Monster.all.each do |x|
        x.name = ""
        x.description = ""
        x.combat_and_tactics = ""
        x.habitat_and_society = ""
        x.ecology = ""
        x.attack_description = ""
        x.health = 0
        x.template = false
        x.size = ""
        x.weight = ""
        x.intelligence = ""
        x.fatigue_factor = 0
        x.crawl = 0
        x.walk = 0
        x.jog = 0
        x.run = 0
        x.sprint = 0
        x.physical_save = 0
        x.mental_save = 0
        x.dodge_save = 0
        x.activity_cycle = ""
        x.no_appearing = ""
        x.chance_in_lair = 0
        x.frequency = ""
        x.alignment = ""
        x.vision_type = ""
        x.awareness_and_senses = ""
        x.habitat = ""
        x.diet = ""
        x.organization = ""
        x.climate = ""
        x.medicinal_yield = ""
        x.spell_component_yield = ""
        x.hide_or_trophy = ""
        x.treasure = ""
        x.edible = ""
        x.other_yield = ""
        x.exp_value = 0
        x.will_factor = 0
        x.speed = 0
        x.attack = 0
        x.init = 0
        x.defense = 0
        x.damage_reduction = 0
        x.reach = ""
        x.damage = 0
        x.top_save = 0
        x.top_threshold = 0
      end

      Proficiency.all.each do |x|
        x.name = ""
        x.description = ""
        x.requirements = ""
        x.bp_cost = 0
      end

      Race.all.each do |x|
        x.name = ""
        x.description = ""
        x.str_mod = 0
        x.int_mod = 0
        x.wis_mod = 0
        x.dex_mod = 0
        x.con_mod = 0
        x.lks_mod = 0
        x.cha_mod = 0
        x.hp_size_adjustment = 0
        x.defense_adjustment_vs_large = 0
        x.defense_adjustment = 0
        x.hide_in_natural = 0
        x.base_movement = 0
        x.reach_adjustment = 0
        x.size = ""
        x.knock_back_size = ""
        x.low_light_vision = false
        x.init_die_bonus = false
        x.male_height = 0
        x.female_height = 0
        x.male_weight = 0
        x.female_weight = 0
        x.lifespan = 0
      end

      Skill.all.each do |x|
        x.name = ""
        x.description = ""
        x.bp_cost = 0
        x.main_attr = ""
        x.other_attr = ""
        x.third_attr = ""
        x.universal = false
        x.prerequisite = ""
        x.materials = ""
        x.unskilled = ""
        x.novice = ""
        x.average = ""
        x.advanced = ""
        x.expert = ""
        x.master = ""
      end

      Specialization.all.each do |x|
        x.value = 0
      end

      Spell.all.each do |x|
        x.name = ""
        x.description = ""
        x.spellpoints = 0
        x.spell_type = ""
        x.verbal = false
        x.somatic = false
        x.material_component = ""
        x.casting_time = 0
        x.duration = 0
        x.volume_of_effect_type = ""
        x.volume_of_effect = 0
        x.volume_increase = 0
        x.volume_increase_cost = 0
        x.range = 0
        x.range_increase = 0
        x.range_increase_cost = 0
        x.target_damage = ""
        x.target_damage_increase = ""
        x.target_damage_increase_cost = 0
        x.area_damage = ""
        x.area_damage_increase = ""
        x.area_damage_increase_cost = 0
        x.special_increase1 = ""
        x.special_increase1_cost = 0
        x.special_increase2 = ""
        x.special_increase2_cost = 0
        x.saving_throw = ""
        x.saving_throw_result = ""
        x.bounce_damage = false
        x.damage_type = ""
        x.duration_increase = 0
        x.duration_increase_cost = 0
      end

      Talent.all.each do |x|
        x.name = ""
        x.description = ""
        x.requirements = ""
        x.bp_cost = 0
      end
    end
end
