development:
  adapter: postgresql
  database: hmt_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: hmt_test
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: hmt_production
  pool: 5
  timeout: 5000
