# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d84f16118f64d259fb977bd7ba24bacdfa30b1706cdd5f994fef585dee0265f9b1d610d0037bc2cd760763e6f4ea0e3a85758d4122261b001b79b3886c7b92d

test:
  secret_key_base: c029a81eb322de77b05746d1d7c71a90bfd28cdc445d3de6f1a980a64fce266454222f185e405b7ed5f02e8ef393c8883f3ab0d435b3316ee2b85614aec3fe6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
