class AddDefaultValues < ActiveRecord::Migration
  def change
    change_column_default :ability_scores, :ability, ""
    change_column_default :ability_scores, :value_range, ""
    change_column_default :ability_scores, :feat_of_strength, 0
    change_column_default :ability_scores, :lift, 0
    change_column_default :ability_scores, :carry, 0
    change_column_default :ability_scores, :drag, 0
    change_column_default :ability_scores, :damage_mod, 0
    change_column_default :ability_scores, :init_mod, 0
    change_column_default :ability_scores, :speed_mod, 0
    change_column_default :ability_scores, :attack_mod, 0
    change_column_default :ability_scores, :defense_mod, 0
    change_column_default :ability_scores, :turning_mod, 0
    change_column_default :ability_scores, :feat_of_agility, 0
    change_column_default :ability_scores, :mental_saving_throw_bonus, 0
    change_column_default :ability_scores, :dodge_saving_throw_bonus, 0
    change_column_default :ability_scores, :physical_saving_throw_bonus, 0
    change_column_default :ability_scores, :morale_mod, 0
    change_column_default :ability_scores, :min, 0
    change_column_default :ability_scores, :max, 0
    change_column_default :ability_scores, :max_spells_per_level, 0
    change_column_default :ability_scores, :chance_to_learn_spell, 0

    change_column_default :characters, :strength, 0
    change_column_default :characters, :intelligence, 0
    change_column_default :characters, :wisdom, 0
    change_column_default :characters, :dexterity, 0
    change_column_default :characters, :constitution, 0
    change_column_default :characters, :looks, 0
    change_column_default :characters, :charisma, 0
    change_column_default :characters, :honor, 0
    change_column_default :characters, :fame, 0
    change_column_default :characters, :health, 0
    change_column_default :characters, :name, ""
    change_column_default :characters, :alignment, "LG"
    change_column_default :characters, :sex, "M"
    change_column_default :characters, :age, 0
    change_column_default :characters, :height, 0
    change_column_default :characters, :weight, 0
    change_column_default :characters, :hair, "black"
    change_column_default :characters, :eyes, "brown"
    change_column_default :characters, :handedness, "L"
    change_column_default :characters, :trade_coins, ""
    change_column_default :characters, :copper, 0
    change_column_default :characters, :silver, 0
    change_column_default :characters, :gold, 0
    change_column_default :characters, :user_id, 0
    change_column_default :characters, :mentor_id, 0
    change_column_default :characters, :left_hand_item_id, 0
    change_column_default :characters, :right_hand_item_id, 0
    change_column_default :characters, :body_item_id, 0
    change_column_default :characters, :character_class_id, 0
    change_column_default :characters, :race_id, 0
    change_column_default :characters, :finished, false

    change_column_default :item_instances, :durability, 0
    change_column_default :item_instances, :attack_mod, 0
    change_column_default :item_instances, :speed_mod, 0
    change_column_default :item_instances, :init_mod, 0
    change_column_default :item_instances, :defense_mod, 0
    change_column_default :item_instances, :damage_mod, 0
    change_column_default :item_instances, :damage_reduction, 0
    change_column_default :item_instances, :magic_level, 0
    change_column_default :item_instances, :init_die_mod, 0
    change_column_default :item_instances, :display, false
    change_column_default :item_instances, :name, ""

    change_column_default :items, :attack_mod, 0
    change_column_default :items, :speed_mod, 0
    change_column_default :items, :init_mod, 0
    change_column_default :items, :defense_mod, 0
    change_column_default :items, :damage_mod, 0
    change_column_default :items, :damage_reduction, 0
    change_column_default :items, :magic_level, 0
    change_column_default :items, :weight, 0
    change_column_default :items, :cover_value, 0
    change_column_default :items, :location, "arm"
    change_column_default :items, :damage, ""
    change_column_default :items, :shield_size, ""
    change_column_default :items, :armor_type, ""
    change_column_default :items, :name, ""
    change_column_default :items, :description, ""
    change_column_default :items, :attack_speed, 0
    change_column_default :items, :jab_speed, 0
    change_column_default :items, :reach, 0
    change_column_default :items, :buy_cost, 0
    change_column_default :items, :sell_value, 0
    change_column_default :items, :damage_type, ""
    change_column_default :items, :heal_value, 0
    change_column_default :items, :item_type, ""
    change_column_default :items, :high_avail, 0
    change_column_default :items, :med_avail, 0
    change_column_default :items, :low_avail, 0
    change_column_default :items, :init_die_mod, 0
    change_column_default :items, :movement_rate_reduction, 0
    change_column_default :items, :crouching_cover_value, 0
    change_column_default :items, :shield_damage, ""
    change_column_default :items, :str_required, 0
    change_column_default :items, :skill_level, ""
    change_column_default :items, :dismount, false
    change_column_default :items, :hvy_armor, 0
    rename_column :items, :hvy_armor, :heavy_armor
    change_column_default :items, :set_for_charge, false
    change_column_default :items, :pole_arm_defense, ""
    change_column_default :items, :phalanx, 0
    change_column_default :items, :size, ""
    change_column_default :items, :max_range, 0
    change_column_default :items, :range_short, 0
    change_column_default :items, :range_medium, 0
    change_column_default :items, :range_long, 0
    change_column_default :items, :range_maximum, 0
    change_column_default :items, :proficiency_id, 0
    change_column_default :items, :two_handed, false
    change_column_default :items, :mounted, false
    change_column_default :items, :sword, false
    change_column_default :items, :capacity_pounds, 0
    change_column_default :items, :capacity_gallons, 0
    change_column_default :items, :number_of_days, 0
    change_column_default :items, :requires_preparation, false
    change_column_default :items, :distance, 0

    change_column_default :levels, :level_value, 0
    change_column_default :levels, :init_mod, 0
    change_column_default :levels, :attack_mod, 0
    change_column_default :levels, :speed_mod, 0
    change_column_default :levels, :spell_points, 0
    change_column_default :levels, :stvsspells, 0
    change_column_default :levels, :addedspells, ""
    rename_column :levels, :addedspells, :added_spells
    change_column_default :levels, :rangedspeedmod, 0
    rename_column :levels, :rangedspeedmod, :ranged_speed_mod
    change_column_default :levels, :initiativediemod, 0
    rename_column :levels, :initiativediemod, :init_die_mod
    change_column_default :levels, :hitdice, ""
    rename_column :levels, :hitdice, :hit_dice

    change_column_default :monsters, :name, ""
    change_column_default :monsters, :description, ""
    change_column_default :monsters, :combat_and_tactics, ""
    change_column_default :monsters, :habitat_and_society, ""
    change_column_default :monsters, :ecology, ""
    change_column_default :monsters, :attack_description, ""
    change_column_default :monsters, :health, 0
    change_column_default :monsters, :template, false
    change_column_default :monsters, :size, ""
    change_column_default :monsters, :weight, ""
    change_column_default :monsters, :intelligence, ""
    change_column_default :monsters, :fatigue_factor, 0
    change_column_default :monsters, :crawl, 0
    change_column_default :monsters, :walk, 0
    change_column_default :monsters, :jog, 0
    change_column_default :monsters, :run, 0
    change_column_default :monsters, :sprint, 0
    change_column_default :monsters, :physical_save, 0
    change_column_default :monsters, :mental_save, 0
    change_column_default :monsters, :dodge_save, 0
    change_column_default :monsters, :activity_cycle, ""
    change_column_default :monsters, :no_appearing, ""
    change_column_default :monsters, :chance_in_lair, 0
    change_column_default :monsters, :frequency, ""
    change_column_default :monsters, :alignment, ""
    change_column_default :monsters, :vision_type, ""
    change_column_default :monsters, :awareness_and_senses, ""
    change_column_default :monsters, :habitat, ""
    change_column_default :monsters, :diet, ""
    change_column_default :monsters, :organization, ""
    change_column_default :monsters, :climate, ""
    change_column_default :monsters, :medicinal_yield, ""
    change_column_default :monsters, :spell_component_yield, ""
    change_column_default :monsters, :hide_or_trophy, ""
    change_column_default :monsters, :treasure, ""
    change_column_default :monsters, :edible, ""
    change_column_default :monsters, :other_yield, ""
    change_column_default :monsters, :exp_value, 0
    change_column_default :monsters, :will_factor, 0
    change_column_default :monsters, :speed, 0
    change_column_default :monsters, :attack, 0
    change_column_default :monsters, :init, 0
    change_column_default :monsters, :defense, 0
    change_column_default :monsters, :damage_reduction, 0
    change_column_default :monsters, :reach, ""
    change_column_default :monsters, :damage, 0
    change_column_default :monsters, :top_save, 0
    change_column_default :monsters, :top_threshold, 0

    change_column_default :proficiencies, :name, ""
    change_column_default :proficiencies, :description, ""
    change_column_default :proficiencies, :requirements, ""
    change_column_default :proficiencies, :bp_cost, 0

    change_column_default :races, :name, ""
    change_column_default :races, :description, ""
    change_column_default :races, :str_mod, 0
    change_column_default :races, :int_mod, 0
    change_column_default :races, :wis_mod, 0
    change_column_default :races, :dex_mod, 0
    change_column_default :races, :con_mod, 0
    change_column_default :races, :lks_mod, 0
    change_column_default :races, :cha_mod, 0
    change_column_default :races, :hpsizeadj, 0
    rename_column :races, :hpsizeadj, :hp_size_adjustment
    change_column_default :races, :defadjvslarge, 0
    rename_column :races, :defadjvslarge, :defense_adjustment_vs_large
    change_column_default :races, :defadj, 0
    rename_column :races, :defadj, :defense_adjustment
    change_column_default :races, :hideinnatsur, 0
    rename_column :races, :hideinnatsur, :hide_in_natural
    change_column_default :races, :basemv, 0
    rename_column :races, :basemv, :base_movement
    change_column_default :races, :reachadj, 0
    rename_column :races, :reachadj, :reach_adjustment
    change_column_default :races, :size, ""
    change_column_default :races, :knockbacksize, ""
    rename_column :races, :knockbacksize, :knock_back_size
    change_column_default :races, :lowlightvision, false
    rename_column :races, :lowlightvision, :low_light_vision
    change_column_default :races, :initdiebonus, false
    rename_column :races, :initdiebonus, :init_die_bonus
    change_column_default :races, :maleheight, 0
    rename_column :races, :maleheight, :male_height
    change_column_default :races, :femaleheight, 0
    rename_column :races, :femaleheight, :female_height
    change_column_default :races, :maleweight, 0
    rename_column :races, :maleweight, :male_weight
    change_column_default :races, :femaleweight, 0
    rename_column :races, :femaleweight, :female_weight
    change_column_default :races, :lifespan, 0

    change_column_default :skills, :name, ""
    change_column_default :skills, :description, ""
    change_column_default :skills, :bp_cost, 0
    change_column_default :skills, :main_attr, ""
    change_column_default :skills, :other_attr, ""
    change_column_default :skills, :third_attr, ""
    change_column_default :skills, :universal, false
    change_column_default :skills, :prerequisite, ""
    change_column_default :skills, :materials, ""
    change_column_default :skills, :unskilled, ""
    change_column_default :skills, :novice, ""
    change_column_default :skills, :average, ""
    change_column_default :skills, :advanced, ""
    change_column_default :skills, :expert, ""
    change_column_default :skills, :master, ""

    change_column_default :specializations, :value, 0

    change_column_default :spells, :name, ""
    change_column_default :spells, :description, ""
    change_column_default :spells, :spellpoints, 0
    change_column_default :spells, :spell_type, ""
    change_column_default :spells, :verbal, false
    change_column_default :spells, :somatic, false
    change_column_default :spells, :material_component, ""
    change_column_default :spells, :casting_time, 0
    change_column_default :spells, :duration, 0
    change_column_default :spells, :volume_of_effect_type, ""
    change_column_default :spells, :volume_of_effect, 0
    change_column_default :spells, :volume_increase, 0
    change_column_default :spells, :volume_increase_cost, 0
    change_column_default :spells, :range, 0
    change_column_default :spells, :range_increase, 0
    change_column_default :spells, :range_increase_cost, 0
    change_column_default :spells, :target_damage, ""
    change_column_default :spells, :target_damage_increase, ""
    change_column_default :spells, :target_damage_increase_cost, 0
    change_column_default :spells, :area_damage, ""
    change_column_default :spells, :area_damage_increase, ""
    change_column_default :spells, :area_damage_increase_cost, 0
    change_column_default :spells, :special_increase1, ""
    change_column_default :spells, :special_increase1_cost, 0
    change_column_default :spells, :special_increase2, ""
    change_column_default :spells, :special_increase2_cost, 0
    change_column_default :spells, :saving_throw, ""
    change_column_default :spells, :saving_throw_result, ""
    change_column_default :spells, :bounce_damage, false
    change_column_default :spells, :damage_type, ""
    change_column_default :spells, :duration_increase, 0
    change_column_default :spells, :duration_increase_cost, 0

    change_column_default :talents, :name, ""
    change_column_default :talents, :description, ""
    change_column_default :talents, :requirements, ""
    change_column_default :talents, :bp_cost, 0

  end
end
